INSERT INTO PUBLIC.genre(type) VALUES
  ('Documental literature'),
  ('Detectives and thrillers'),
  ('Computers and Internet'),
  ('Poetry'),
  ('Science and education');

INSERT INTO PUBLIC.Authors (firstname, lastname) VALUES
  ('Igor', 'Prokopenko'),
  ('Henri', 'Troyat'),
  ('Dick', 'Francis'),
  ('Natalia', 'Andreeva'),
  ('King', 'Stephen'),
  ('Michael', 'Stelzner'),
  ('Albitov', 'Andrew'),
  ('Yuri', 'Polyakov'),
  ('Arthur', 'Wiggins'),
  ('Yakov', 'Perelman');

INSERT INTO PUBLIC.book (title, author, publish_year, genre, description, total_amount) VALUES
  ('Aliens of national importance', 1, 2013, 0, 'This book is the first domestic, based on documents from military archives, about aliens, flying saucers, contacts with extraterrestrial civilizations and the parallel worlds of the famous documentary, author and host of the program "Military Secret" Igor Prokopenko. The author worked on the book for twenty years, it included a truly sensational materials: reports of military pilots of UFO attacks, reports of commanders of nuclear submarines of encounters with objects of extraterrestrial origin, reports chief spetsrazvedki Navy directive Navy Commander ... In this book, there is no single line of rumors and speculation. Each given fact, no matter how it may seem fantastic, documented or event participants. Do UFOs exist? Absolutely accurate answer, you will learn from this book ...', 10),
  ('Peter the First', 2, 1980, 0, 'Myths about Peter the Great, brilliant reformer who saved the Russian state from imminent death and at the same time, "The Departed, disrupt Russia with its circular orbit to the comet zashvyrnut in space", almost the Antichrist, overthrew all moral principles and traditions continue haunt the minds and cause controversy today. Why does the human memory Ivan the Terrible - "the mad monster," and Peter the Great, in his cruelty surpassed it remains "immaculate genius"? Above all this reflects the famous French historian Henri Troyat and offers readers his version of the history of the life and reign of Peter.', 10),
  ('Devil''s cocktail', 3, 1972, 1, 'From the moment the actor Link inherits the South African Republic, begin to pursue his mysterious accidents. Realizing that someone wants him dead, Link tries to get ahead of the mysterious killer', 10),
  ('I''ll be you', 4, 2010, 1, 'This man knew a great secret. The mystery of death. He knew something that others avoided until the last moment, still believing that this is not the last gasp. And he knew. He did not care, live or die. He was able to defeat his fear of death. He saw the dying, and once had almost died himself. And get him to share this secret nobody could. No force and persuasion. This could only happen voluntarily. He will, of condescension to pathetic little people who do not want to take up the eternal to the last breath, and so afraid of the Elect. Those dedicated to the mystery of death, who could help them and their ... Release of this fear.', 10),
  ('The Shawshank Redemption', 5, 1999, 1, 'The book "The Shawshank Redemption" connects the horrors of prison life and the fantasy of escape. Shawshank - the name of the prison. Andy, vice president of solid bank, was sentenced to two life sentences for the murder of his wife and her lover. He is serving his sentence in Shawshank prison, where is all the circles of hell, showing remarkable courage, tenacity and composure. If you are not yet 30, and you get a life, then Valium to worse: the output of Redemption for you will not.', 10),
  ('Content marketing. New methods of customer acquisition in the Internet age', 6, 2012, 2, 'Michael Stelzner - a recognized expert in the field of social media, the creator of one of the most popular marketing blogs in social networks SocialMediaExaminer.com (more than 150 000 subscribers). The book Stelzner tells about the different types of content that you can publish on your website, blog, a page on the social network and help you attract the attention of potential customers. The author explains how to plan the work for the preparation of the content, how to engage in its creation of renowned experts and how to use social media for its promotion. He also gives valuable advice on working with text, video reel, to organize events and draws attention to the details, which will increase the attractiveness of your content to users. This book - a useful guide for those who want to master the content-marketing tools and use it to win the favor of the Internet audience.', 10),
  ('Facebook: how to find 100,000 friends to your business for free', 7, 2011, 2, 'Very few people understand how to use social media for business. Meanwhile, a powerful and practically free tool that allows you to gather around us hundreds of thousands of friends and have a month to a million contacts with actual and potential customers. It takes only a little time to create a company page on Facebook and "Vkontakte", discipline in support of communication with its visitors and the implementation of a number of recommendations, and that you will find in this edition. The author has already "stepped on a rake" for you and tell you about errors and successful solutions. This book will be most useful to marketers, PR-professionals, entrepreneurs. And also for those who want to understand how social networks help businesses.', 10),
  ('One hundred days before the order', 8, 2005 , 3, 'In a new book by the famous writer Yuri Polyakov became the most famous tale of "One hundred days before the order" a modern army, still causes heated debates and divergent views. Also in this edition for the first time under one cover are collected other works of the author devoted to the military theme, written at different times and in different genres: prose, poetry, journalism, screenwriting. At the court of the reader is presented witty film story "Mom''s Story", have never been published. The collection will be of interest to those who have already passed the army school, and for those who are just getting ready to serve, this book can be a real textbook of a soldier''s life.', 10),
  ('Five unsolved problems of science', 9, 2014, 4, 'American scientists Arthur Wiggins and Charles Wynn just detailed and humorous talk about the major problems of science, the solution of which scientists around the world are fighting. Astronomy. Why the universe is expanding, but the rate of expansion is increasing? Physics. Why do some particles have mass while others - not? Chemistry. What chemical reactions atoms are pushed to the formation of the first living beings? Biology. What is the total device and destination proteome? Geology. Is it possible to accurate long-term weather forecast? The author introduce the events that put these issues, discuss the existing theories, including string theory, the chaos, the human genome and protein folding, allow readers to take part in the reflections on the ideas proposed. The book tells the story of the biggest problems of astronomy, physics, chemistry, biology and geology, on which scientists are now working. The author consider the opening that led to these problems, are familiar with the work on their solution and discuss new theories, including string theory, the chaos, the human genome and protein folding. For a wide range of readers. Pictures Sidney Harris', 10),
  ('Physics at every step', 10, 2009, 4, 'One of the best benefits of classical physics. Interesting stories, instructive experiments, interesting facts will teach the inquisitive reader to notice the simplest physical phenomena and understand their nature.', 10),
  ('Selected poems', 4, 2015, 3, 'Selected Poems known Leningrad poet. Included love, military, philosophical poems, ballads, and allegories, some fragments of verse from the poet''s ironic fantasy.', 10),
  ('Secrets of the universe', 9, 2008, 4, 'The book is based on the latest scientific data paints a picture of the universe in its development - from early concepts to mifopoeticheskih modern cosmological panorama. The author refers to the mysteries of the dispensation of the most difficult and pressing problems of astronomy, astrology, astrophysics, paranormal, space contacts. Text Only. In the book 140 illustrations.', 10);
